#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RX_DataUpdata
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ALTDataBase")]
	public partial class MSEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public MSEDataContext() : 
				base(global::RX_DataUpdata.Properties.Settings.Default.ALTDataBaseConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public MSEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewExp")]
		public ISingleResult<NewExpResult> NewExp(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bid", DbType="NVarChar(128)")] string bid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string pid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> b1t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> b2t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> b3t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string b3m, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PoleDim", DbType="Float")] System.Nullable<double> poleDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Presstime", DbType="Float")] System.Nullable<double> presstime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weldele", DbType="Float")] System.Nullable<double> weldele, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> weldtime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keeptime", DbType="Float")] System.Nullable<double> keeptime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pressure", DbType="Float")] System.Nullable<double> pressure, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SportDim", DbType="Float")] System.Nullable<double> sportDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RongheDim", DbType="Float")] System.Nullable<double> rongheDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="NVarChar(255)")] string remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zaojian", DbType="Bit")] System.Nullable<bool> zaojian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FistPoint", DbType="Bit")] System.Nullable<bool> fistPoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPoint", DbType="Bit")] System.Nullable<bool> endPoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zhanfu", DbType="Bit")] System.Nullable<bool> zhanfu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LieWen", DbType="Bit")] System.Nullable<bool> lieWen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeiJian", DbType="Bit")] System.Nullable<bool> feiJian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="YaHeng", DbType="Bit")] System.Nullable<bool> yaHeng, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaiGuanNG", DbType="Bit")] System.Nullable<bool> waiGuanNG, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LianXuHanDian", DbType="Bit")] System.Nullable<bool> lianXuHanDian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanJieJianXi", DbType="Bit")] System.Nullable<bool> hanJieJianXi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FwPicture", DbType="VarChar(128)")] string fwPicture, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BwPicture", DbType="VarChar(128)")] string bwPicture, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rnum1", DbType="Int")] ref System.Nullable<int> rnum1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bid, pid, b1t, b2t, b3t, b3m, poleDim, presstime, weldele, weldtime, keeptime, pressure, sportDim, rongheDim, remarks, zaojian, fistPoint, endPoint, zhanfu, lieWen, feiJian, yaHeng, waiGuanNG, lianXuHanDian, hanJieJianXi, fwPicture, bwPicture, rnum1);
			rnum1 = ((System.Nullable<int>)(result.GetParameterValue(27)));
			return ((ISingleResult<NewExpResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdataExp")]
		public ISingleResult<UpdataExpResult> UpdataExp(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bid", DbType="NVarChar(128)")] string bid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string pid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> b1t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> b2t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> b3t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string b3m, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PoleDim", DbType="Float")] System.Nullable<double> poleDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Presstime", DbType="Float")] System.Nullable<double> presstime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weldele", DbType="Float")] System.Nullable<double> weldele, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> weldtime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keeptime", DbType="Float")] System.Nullable<double> keeptime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pressure", DbType="Float")] System.Nullable<double> pressure, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SportDim", DbType="Float")] System.Nullable<double> sportDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RongheDim", DbType="Float")] System.Nullable<double> rongheDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="NVarChar(255)")] string remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zaojian", DbType="Bit")] System.Nullable<bool> zaojian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FistPoint", DbType="Bit")] System.Nullable<bool> fistPoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPoint", DbType="Bit")] System.Nullable<bool> endPoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zhanfu", DbType="Bit")] System.Nullable<bool> zhanfu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LieWen", DbType="Bit")] System.Nullable<bool> lieWen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeiJian", DbType="Bit")] System.Nullable<bool> feiJian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="YaHeng", DbType="Bit")] System.Nullable<bool> yaHeng, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaiGuanNG", DbType="Bit")] System.Nullable<bool> waiGuanNG, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LianXuHanDian", DbType="Bit")] System.Nullable<bool> lianXuHanDian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanJieJianXi", DbType="Bit")] System.Nullable<bool> hanJieJianXi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FwPicture", DbType="VarChar(128)")] string fwPicture, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BwPicture", DbType="VarChar(128)")] string bwPicture, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rnum1", DbType="Int")] ref System.Nullable<int> rnum1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bid, pid, b1t, b2t, b3t, b3m, poleDim, presstime, weldele, weldtime, keeptime, pressure, sportDim, rongheDim, remarks, zaojian, fistPoint, endPoint, zhanfu, lieWen, feiJian, yaHeng, waiGuanNG, lianXuHanDian, hanJieJianXi, fwPicture, bwPicture, rnum1);
			rnum1 = ((System.Nullable<int>)(result.GetParameterValue(27)));
			return ((ISingleResult<UpdataExpResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SerchExp")]
		public int SerchExp(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string pid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] ref System.Nullable<double> b1t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] ref System.Nullable<double> b2t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] ref System.Nullable<double> b3t, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] ref string b3m, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PoleDim", DbType="Float")] ref System.Nullable<double> poleDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Presstime", DbType="Float")] ref System.Nullable<double> presstime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weldele", DbType="Float")] ref System.Nullable<double> weldele, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] ref System.Nullable<double> weldtime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keeptime", DbType="Float")] ref System.Nullable<double> keeptime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pressure", DbType="Float")] ref System.Nullable<double> pressure, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SportDim", DbType="Float")] ref System.Nullable<double> sportDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RongheDim", DbType="Float")] ref System.Nullable<double> rongheDim, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="NVarChar(255)")] ref string remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zaojian", DbType="Bit")] ref System.Nullable<bool> zaojian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FistPoint", DbType="Bit")] ref System.Nullable<bool> fistPoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPoint", DbType="Bit")] ref System.Nullable<bool> endPoint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zhanfu", DbType="Bit")] ref System.Nullable<bool> zhanfu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LieWen", DbType="Bit")] ref System.Nullable<bool> lieWen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeiJian", DbType="Bit")] ref System.Nullable<bool> feiJian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="YaHeng", DbType="Bit")] ref System.Nullable<bool> yaHeng, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaiGuanNG", DbType="Bit")] ref System.Nullable<bool> waiGuanNG, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LianXuHanDian", DbType="Bit")] ref System.Nullable<bool> lianXuHanDian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanJieJianXi", DbType="Bit")] ref System.Nullable<bool> hanJieJianXi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FwPicture", DbType="VarChar(128)")] ref string fwPicture, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BwPicture", DbType="VarChar(128)")] ref string bwPicture, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ret", DbType="Int")] ref System.Nullable<int> ret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pid, b1t, b2t, b3t, b3m, poleDim, presstime, weldele, weldtime, keeptime, pressure, sportDim, rongheDim, remarks, zaojian, fistPoint, endPoint, zhanfu, lieWen, feiJian, yaHeng, waiGuanNG, lianXuHanDian, hanJieJianXi, fwPicture, bwPicture, ret);
			b1t = ((System.Nullable<double>)(result.GetParameterValue(1)));
			b2t = ((System.Nullable<double>)(result.GetParameterValue(2)));
			b3t = ((System.Nullable<double>)(result.GetParameterValue(3)));
			b3m = ((string)(result.GetParameterValue(4)));
			poleDim = ((System.Nullable<double>)(result.GetParameterValue(5)));
			presstime = ((System.Nullable<double>)(result.GetParameterValue(6)));
			weldele = ((System.Nullable<double>)(result.GetParameterValue(7)));
			weldtime = ((System.Nullable<double>)(result.GetParameterValue(8)));
			keeptime = ((System.Nullable<double>)(result.GetParameterValue(9)));
			pressure = ((System.Nullable<double>)(result.GetParameterValue(10)));
			sportDim = ((System.Nullable<double>)(result.GetParameterValue(11)));
			rongheDim = ((System.Nullable<double>)(result.GetParameterValue(12)));
			remarks = ((string)(result.GetParameterValue(13)));
			zaojian = ((System.Nullable<bool>)(result.GetParameterValue(14)));
			fistPoint = ((System.Nullable<bool>)(result.GetParameterValue(15)));
			endPoint = ((System.Nullable<bool>)(result.GetParameterValue(16)));
			zhanfu = ((System.Nullable<bool>)(result.GetParameterValue(17)));
			lieWen = ((System.Nullable<bool>)(result.GetParameterValue(18)));
			feiJian = ((System.Nullable<bool>)(result.GetParameterValue(19)));
			yaHeng = ((System.Nullable<bool>)(result.GetParameterValue(20)));
			waiGuanNG = ((System.Nullable<bool>)(result.GetParameterValue(21)));
			lianXuHanDian = ((System.Nullable<bool>)(result.GetParameterValue(22)));
			hanJieJianXi = ((System.Nullable<bool>)(result.GetParameterValue(23)));
			fwPicture = ((string)(result.GetParameterValue(24)));
			bwPicture = ((string)(result.GetParameterValue(25)));
			ret = ((System.Nullable<int>)(result.GetParameterValue(26)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateBoardPictureAndRemark")]
		public int UpdateBoardPictureAndRemark([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BID", DbType="VarChar(128)")] string bID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FwPicture", DbType="VarChar(128)")] string fwPicture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BwPicture", DbType="VarChar(128)")] string bwPicture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReMark", DbType="NVarChar(255)")] string reMark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ret", DbType="Int")] ref System.Nullable<int> ret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bID, fwPicture, bwPicture, reMark, ret);
			ret = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CreatBoardPictureAndRemark")]
		public int CreatBoardPictureAndRemark([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BID", DbType="VarChar(128)")] string bID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FwPicture", DbType="VarChar(128)")] string fwPicture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BwPicture", DbType="VarChar(128)")] string bwPicture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReMark", DbType="NVarChar(255)")] string reMark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ret", DbType="Int")] ref System.Nullable<int> ret)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bID, fwPicture, bwPicture, reMark, ret);
			ret = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class NewExpResult
	{
		
		private string _Column1;
		
		public NewExpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(4000)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class UpdataExpResult
	{
		
		private string _Column1;
		
		public UpdataExpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(4000)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
