<?xml version="1.0" encoding="utf-8"?><Database Name="ALTDataBase" Class="MSEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RX_YFB_YF079\RXYF;Initial Catalog=ALTDataBase;Persist Security Info=True;User ID=sa" SettingsObjectName="RX_DataUpdata.Properties.Settings" SettingsPropertyName="ALTDataBaseConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="dbo.NewExp" Method="NewExp">
    <Parameter Name="Bid" Parameter="bid" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="pid" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="b1t" Type="System.Double" DbType="Float" />
    <Parameter Name="b2t" Type="System.Double" DbType="Float" />
    <Parameter Name="b3t" Type="System.Double" DbType="Float" />
    <Parameter Name="b3m" Type="System.String" DbType="NChar(50)" />
    <Parameter Name="PoleDim" Parameter="poleDim" Type="System.Double" DbType="Float" />
    <Parameter Name="Presstime" Parameter="presstime" Type="System.Double" DbType="Float" />
    <Parameter Name="Weldele" Parameter="weldele" Type="System.Double" DbType="Float" />
    <Parameter Name="weldtime" Type="System.Double" DbType="Float" />
    <Parameter Name="Keeptime" Parameter="keeptime" Type="System.Double" DbType="Float" />
    <Parameter Name="Pressure" Parameter="pressure" Type="System.Double" DbType="Float" />
    <Parameter Name="SportDim" Parameter="sportDim" Type="System.Double" DbType="Float" />
    <Parameter Name="RongheDim" Parameter="rongheDim" Type="System.Double" DbType="Float" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Zaojian" Parameter="zaojian" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FistPoint" Parameter="fistPoint" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EndPoint" Parameter="endPoint" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Zhanfu" Parameter="zhanfu" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LieWen" Parameter="lieWen" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FeiJian" Parameter="feiJian" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="YaHeng" Parameter="yaHeng" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="WaiGuanNG" Parameter="waiGuanNG" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LianXuHanDian" Parameter="lianXuHanDian" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="HanJieJianXi" Parameter="hanJieJianXi" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FwPicture" Parameter="fwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="BwPicture" Parameter="bwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="Rnum1" Parameter="rnum1" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="NewExpResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdataExp" Method="UpdataExp">
    <Parameter Name="Bid" Parameter="bid" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="pid" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="b1t" Type="System.Double" DbType="Float" />
    <Parameter Name="b2t" Type="System.Double" DbType="Float" />
    <Parameter Name="b3t" Type="System.Double" DbType="Float" />
    <Parameter Name="b3m" Type="System.String" DbType="NChar(50)" />
    <Parameter Name="PoleDim" Parameter="poleDim" Type="System.Double" DbType="Float" />
    <Parameter Name="Presstime" Parameter="presstime" Type="System.Double" DbType="Float" />
    <Parameter Name="Weldele" Parameter="weldele" Type="System.Double" DbType="Float" />
    <Parameter Name="weldtime" Type="System.Double" DbType="Float" />
    <Parameter Name="Keeptime" Parameter="keeptime" Type="System.Double" DbType="Float" />
    <Parameter Name="Pressure" Parameter="pressure" Type="System.Double" DbType="Float" />
    <Parameter Name="SportDim" Parameter="sportDim" Type="System.Double" DbType="Float" />
    <Parameter Name="RongheDim" Parameter="rongheDim" Type="System.Double" DbType="Float" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Zaojian" Parameter="zaojian" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FistPoint" Parameter="fistPoint" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EndPoint" Parameter="endPoint" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Zhanfu" Parameter="zhanfu" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LieWen" Parameter="lieWen" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FeiJian" Parameter="feiJian" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="YaHeng" Parameter="yaHeng" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="WaiGuanNG" Parameter="waiGuanNG" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LianXuHanDian" Parameter="lianXuHanDian" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="HanJieJianXi" Parameter="hanJieJianXi" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FwPicture" Parameter="fwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="BwPicture" Parameter="bwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="Rnum1" Parameter="rnum1" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="UpdataExpResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SerchExp" Method="SerchExp">
    <Parameter Name="pid" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="b1t" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="b2t" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="b3t" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="b3m" Type="System.String" DbType="NChar(50)" Direction="InOut" />
    <Parameter Name="PoleDim" Parameter="poleDim" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="Presstime" Parameter="presstime" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="Weldele" Parameter="weldele" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="weldtime" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="Keeptime" Parameter="keeptime" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="Pressure" Parameter="pressure" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="SportDim" Parameter="sportDim" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="RongheDim" Parameter="rongheDim" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="Remarks" Parameter="remarks" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Parameter Name="Zaojian" Parameter="zaojian" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="FistPoint" Parameter="fistPoint" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="EndPoint" Parameter="endPoint" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Zhanfu" Parameter="zhanfu" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="LieWen" Parameter="lieWen" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="FeiJian" Parameter="feiJian" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="YaHeng" Parameter="yaHeng" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="WaiGuanNG" Parameter="waiGuanNG" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="LianXuHanDian" Parameter="lianXuHanDian" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="HanJieJianXi" Parameter="hanJieJianXi" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="FwPicture" Parameter="fwPicture" Type="System.String" DbType="VarChar(128)" Direction="InOut" />
    <Parameter Name="BwPicture" Parameter="bwPicture" Type="System.String" DbType="VarChar(128)" Direction="InOut" />
    <Parameter Name="Ret" Parameter="ret" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBoardPictureAndRemark" Method="UpdateBoardPictureAndRemark">
    <Parameter Name="BID" Parameter="bID" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="FwPicture" Parameter="fwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="BwPicture" Parameter="bwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="ReMark" Parameter="reMark" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Ret" Parameter="ret" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreatBoardPictureAndRemark" Method="CreatBoardPictureAndRemark">
    <Parameter Name="BID" Parameter="bID" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="FwPicture" Parameter="fwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="BwPicture" Parameter="bwPicture" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="ReMark" Parameter="reMark" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Ret" Parameter="ret" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>