//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RX_DataUpdata.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5HK1A11\\RXYF;Initial Catalog=RXYF_YECC;Persist Security Info=" +
            "True;User ID=sa")]
        public string RXYF_YECCConnectionString1 {
            get {
                return ((string)(this["RXYF_YECCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5HK1A11\\RXYF;Initial Catalog=RXYF_YECC;Persist Security Info=" +
            "True;User ID=sa;Password=ycc123!")]
        public string RXYF_YECCConnectionString {
            get {
                return ((string)(this["RXYF_YECCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5HK1A11\\RXYF;Initial Catalog=ALTDataBase;Persist Security Inf" +
            "o=True;User ID=sa;Password=ycc123!")]
        public string ALTDataBaseConnectionString {
            get {
                return ((string)(this["ALTDataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5HK1A1I\\RXYF;Initial Catalog=ALTDataBase;Integrated Security=" +
            "True")]
        public string ALTDataBaseConnectionString1 {
            get {
                return ((string)(this["ALTDataBaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5HK1A1I\\RXYF;Initial Catalog=RXYF_YECC;Integrated Security=Tr" +
            "ue")]
        public string RXYF_YECCConnectionString2 {
            get {
                return ((string)(this["RXYF_YECCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RX_YFB_YF079\\RXYF;Initial Catalog=ALTDataBase;Persist Security Info=T" +
            "rue;User ID=sa;Password=ycc123!")]
        public string ALTDataBaseConnectionString2 {
            get {
                return ((string)(this["ALTDataBaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RX_YFB_YF079\\RXYF;Initial Catalog=RXYF_YECC;Persist Security Info=Tru" +
            "e;User ID=sa;Password=ycc123!")]
        public string RXYF_YECCConnectionString3 {
            get {
                return ((string)(this["RXYF_YECCConnectionString3"]));
            }
        }
    }
}
